name: deploy news-api by ZUNO
on: [workflow_dispatch]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: supnobita/ssh-action@master
              with:
                  host: 54.169.185.39
                  username: ubuntu
                  key: ${{ secrets.NEWS_DEV_SECRET }}
                  port: 22
                  envs: GITHUB_RUN_NUMBER
                  script: |
                      cd code/
                      rm -rf news-admin/
                      git clone https://${{ secrets.NEWS_DEV_TOKEN_SSH }}@github.com/zuno90/news-admin.git
                      echo ${{ secrets.NEWS_DEV_TOKEN_SSH }}
                      docker compose up -d news-admin
                    #   cd news-admin
                    #   DOCKER_BUILDKIT=1 docker build -t news-admin:$GITHUB_RUN_NUMBER .
                    #   docker stop news-admin || echo "OK"
                    #   docker rm news-admin || echo "OK"
                      news-admin:$GITHUB_RUN_NUMBER
